model_list:
  - model_name: gpt-4o
    litellm_params:
      api_base: http://127.0.0.1:5001/v1
      model: openai/gpt-4o
      api_key: placeholder

  - model_name: gpt-4.1
    litellm_params:
      api_base: http://127.0.0.1:5001/v1
      model: openai/gpt-4.1
      api_key: placeholder

  - model_name: gpt-5-mini
    litellm_params:
      api_base: http://127.0.0.1:5001/v1
      model: openai/gpt-5-mini
      api_key: placeholder

  - model_name: gpt-4o-mini
    litellm_params:
      api_base: http://127.0.0.1:5001/v1
      model: openai/gpt-4o-mini
      api_key: placeholder

litellm_settings:
  drop_params: true
  set_verbose: true
